services:
  web:
    build: ./docker/php
    container_name: toho-laravel-web
    ports:
      - 80:80
      - 443:443
      - 5173:5173
    volumes:
      - ./docker/apache/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./docker/apache/ssl:/etc/apache2/ssl
      - ./docker/apache/conf.d:/etc/apache2/conf.d
      - ./www:/var/www
      - ./test_data:/test_data

  postgres:
    image: postgres:12-alpine
    container_name: toho-laravel-pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      TZ: "Asia/Tokyo"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
